### ISSUE TITLE
Issue with read_nortek function

### ISSUE THREAD

**Issue by Tkideau** [lkilcher/dolfyn#14] opened 2017-07-06 09:02 UTC
Hello lklicher,
I was planning to develop a Python script to read .vec file when I found your library : very useful ! Many thanks for developing it ! 
I began to use your _read_nortek_ function and it works well on the majority of my .vec file but on some others, it throws this error :
![error](https://user-images.githubusercontent.com/29943170/27903017-c0d8d822-622f-11e7-9cb0-8f79e3ef73c1.png)
I saw a similar issue was raised in the past and partially solved : https://github.com/lkilcher/dolfyn/issues/3
Unfortunately I can't provide you the .vec that are raising the error but the thing I can tell you is that data are generated in continuous mode.
Thank you for your time,
Tkideau

**Comment by Tkideau** [comment] 2017-07-19 11:00
Hello lklicher,
I noted another issue perhaps related to this one : 
when processing some .vec files, the **while loop** in the _findnextid()_ method (<dolfyn.io.nortek>line 966) turns into an infinite loop. Variable **nowid** alternate between values 0 and 165 but never go to 17 (which seems to be the typical termination condition).
I observed the same in the case of "Reached the end of the file." issue. I thus thinking that the problem is around here (**searchcode**, _read_id()_, _read()_ ...).
Hope you will find a bit of time to look at this !
Regards,
Tkideau

**Comment by lkilcher** [comment] 2017-07-25 21:07
Hi and sorry for the slow response. It's extremely hard for me to debug these kinds of errors without the source file. If there is any way to share the data file with me I can assure you I won't share it with anyone else or use it for anything other than debugging. Otherwise, it's really not worth my time to try to guess what the problem is.

**Comment by lkilcher** [comment] 2019-02-27 15:04
Closing this due to lack of: activity and data.

**Closed by lkilcher** 2019-02-27 15:04 UTC
Labels: wontfix
